"use client";

import { Component, lazy, ReactNode, Suspense, useEffect, useRef, useState } from "react";

type RobotId="so101"|"panda";
type ControllerMode="classical"|"vla"|"hybrid";
type GraspMode="physics"|"contact_attachment";
type PhysicsMetrics={contacts:number;left_contact:boolean;right_contact:boolean;normal_force:number;object_slip_velocity:number;object_height:number;grasp_state:string};
type SceneState={frame:number;robot_id?:RobotId;scene_profile?:"playground"|"vla_reference";robot:{joints:number[];finger_joints?:number[];bodies?:{name:string;matrix:number[]}[];ee_position:number[];gripper_open:boolean};objects:{name:string;position:number[]}[];verified:boolean;physics:string;control_mode?:string;simulation_steps?:number;actuator_count?:number;policy_fps?:number;physics_hz?:number;grasp_mode?:string;physics_metrics?:PhysicsMetrics};
type TraceEvent={kind:string;text:string;tone?:"good"|"bad"};
type StreamEvent={type:string;text?:string;error?:string;name?:string;arguments?:Record<string,unknown>;result?:{success:boolean;error?:string};state?:SceneState;verified?:boolean;features?:string[];raw_action?:number[];safe_action?:number[];safety?:string[];action_queue?:number;inference_latency_ms?:number;event?:string;provider?:string};
type VLADebug={queue:number;latency:number;raw:number[];safe:number[];events:string[]};

const RobotScene3D=lazy(()=>import("./RobotScene3D"));
const API_URL=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:8000";
const PUBLIC_DEMO=process.env.NEXT_PUBLIC_PUBLIC_DEMO==="true";
const initialTrace:TraceEvent[]=[{kind:"SYSTEM",text:"Connecting to simulation backend…"}];
const browserDemoState:SceneState={frame:0,robot_id:"panda",robot:{joints:[0,-.785,0,-2.356,0,1.571,.785],finger_joints:[.04,.04],ee_position:[.307,-.37,.927],gripper_open:true},objects:[{name:"red_cube",position:[-.24,.02,.47]},{name:"green_cube",position:[-.08,.17,.47]},{name:"yellow_cube",position:[-.31,.26,.47]},{name:"purple_cube",position:[.04,.29,.47]},{name:"blue_box",position:[.25,.11,.452]}],verified:false,physics:"browser-demo",control_mode:"scripted-browser-demo",simulation_steps:0,actuator_count:0};
const publicOfflineState:SceneState={frame:0,robot_id:"so101",scene_profile:"vla_reference",robot:{joints:[0,.001,-.001,1.57,.001,0],ee_position:[-.005,-.239,.097],gripper_open:false},objects:[{name:"red_cube",position:[0,-.22,.012]},{name:"blue_box",position:[-.18,-.13,.006]}],verified:false,physics:"offline",control_mode:"unavailable",simulation_steps:0,actuator_count:6,policy_fps:15,physics_hz:500};

class SceneErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="threeError">3D preview unavailable. Robot control and camera streams can still be used.</div>:this.props.children}}
function ClientRobotScene({sceneState,running}:{sceneState:SceneState|null;running:boolean}){const[mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);if(!mounted)return <div className="threeLoading">Preparing WebGL workcell…</div>;return <SceneErrorBoundary key={`${sceneState?.robot_id??"none"}-${sceneState?.scene_profile??"none"}`}><Suspense fallback={<div className="threeLoading">Loading official robot meshes…</div>}><RobotScene3D sceneState={sceneState} running={running}/></Suspense></SceneErrorBoundary>}
function describeEvent(event:StreamEvent):TraceEvent|null{
 if(event.type==="run_started")return{kind:"USER",text:event.text??"Task accepted"};
 if(event.type==="observe")return{kind:"OBSERVE",text:event.text??"Captured scene + wrist cameras"};
 if(event.type==="vla_observation")return{kind:"OBSERVATION",text:(event.features??[]).join(" + ")};
 if(event.type==="vla_action")return{kind:"VLA",text:`${event.provider??"policy"} → [${(event.raw_action??[]).map(v=>v.toFixed(3)).join(", ")}]`};
 if(event.type==="safety")return{kind:"SAFETY",text:event.event??"Action accepted",tone:event.event==="ACTION_REJECTED"?"bad":undefined};
 if(event.type==="model")return{kind:"MODEL",text:event.text??"Model response"};
 if(event.type==="tool")return{kind:"TOOL",text:`${event.name}(${JSON.stringify(event.arguments)})`};
 if(event.type==="result")return{kind:"RESULT",text:event.result?.success?"success":event.result?.error??"failed",tone:event.result?.success?"good":"bad"};
 if(event.type==="success")return{kind:"SUCCESS",text:"✓ Verified by simulator",tone:"good"};
 if(event.type==="failure")return{kind:"FAILURE",text:event.error??"Task failed",tone:"bad"};
 if(event.type==="stopped")return{kind:"STOPPED",text:"Stopped by user",tone:"bad"};return null;
}
function Choice<T extends string>({value,current,label,onClick}:{value:T;current:T;label:string;onClick:(v:T)=>void}){return <button type="button" className={value===current?"choice active":"choice"} onClick={()=>onClick(value)}>{label}</button>}

export default function Home(){
 const[prompt,setPrompt]=useState("把红色方块放进蓝色盒子"),[running,setRunning]=useState(false),[online,setOnline]=useState(false),[mode,setMode]=useState<"connecting"|"backend"|"browser">("connecting");
 const[robot,setRobot]=useState<RobotId>("so101"),[controller,setController]=useState<ControllerMode>(PUBLIC_DEMO?"hybrid":"vla"),[grasp,setGrasp]=useState<GraspMode>("physics");
 const[provider,setProvider]=useState("mock"),[sessionId,setSessionId]=useState<string|null>(null),[sceneState,setSceneState]=useState<SceneState|null>(null),[trace,setTrace]=useState<TraceEvent[]>(initialTrace),[cameraVersion,setCameraVersion]=useState(0);
 const[vla,setVla]=useState<VLADebug>({queue:0,latency:0,raw:[],safe:[],events:[]});const socketRef=useRef<WebSocket|null>(null);
 useEffect(()=>{let cancelled=false,createdId:string|undefined;setOnline(false);setMode("connecting");setRunning(false);socketRef.current?.close();
  async function connect(){try{let response:Response|null=null;for(let attempt=0;attempt<3;attempt++){response=await fetch(`${API_URL}/api/sessions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed:Math.floor(Math.random()*10000),robot,controller,brain:controller==="hybrid"?"gemini":"none",policy:"smolvla",grasp_mode:grasp})});if(response.status!==503)break;await new Promise(resolve=>setTimeout(resolve,600*(attempt+1)))}if(!response||!response.ok)throw new Error(`Backend returned ${response?.status??"offline"}`);const payload=await response.json();createdId=payload.session_id;if(cancelled)return;setProvider(payload.model_provider??"mock");setSessionId(createdId!);setSceneState(payload.state);setOnline(true);setMode("backend");setTrace([{kind:"SYSTEM",text:`${robot.toUpperCase()} · ${controller} · ${payload.state.physics}`},{kind:"OBSERVE",text:"Scene RGB + wrist RGB + robot state ready"}]);const socket=new WebSocket(`${API_URL.replace(/^http/,"ws")}/ws/${createdId}`);socketRef.current=socket;socket.onmessage=message=>{const event=JSON.parse(message.data) as StreamEvent;if(event.type==="scene_state"&&event.state){setSceneState(event.state);if(event.state.frame%3===0)setCameraVersion(v=>v+1)}if(event.type==="vla_action")setVla({queue:event.action_queue??0,latency:event.inference_latency_ms??0,raw:event.raw_action??[],safe:event.safe_action??[],events:event.safety??[]});const item=describeEvent(event);if(item)setTrace(items=>[...items,item]);if(event.type==="observe"||event.type==="vla_observation")setCameraVersion(v=>v+1);if(["success","failure","stopped"].includes(event.type))setRunning(false)};socket.onclose=()=>{if(!cancelled)setOnline(false)}}catch{if(cancelled)return;setProvider("browser");setSessionId("browser-demo");setSceneState(PUBLIC_DEMO?publicOfflineState:browserDemoState);setOnline(!PUBLIC_DEMO);setMode("browser");setTrace([{kind:"SYSTEM",text:PUBLIC_DEMO?"Public simulation backend is offline":"Browser fallback ready"},{kind:"OBSERVE",text:PUBLIC_DEMO?"The host computer or secure tunnel is unavailable":"Start the Python backend for live SO-101 MuJoCo"}])}}
  connect();return()=>{cancelled=true;socketRef.current?.close();if(createdId)fetch(`${API_URL}/api/sessions/${createdId}`,{method:"DELETE",keepalive:true}).catch(()=>undefined)}
 },[robot,controller,grasp]);
 async function runTask(){if(!prompt.trim()||!sessionId||running)return;setTrace(items=>[...items,{kind:"USER",text:prompt.trim()}]);setRunning(true);if(mode==="browser"){setTimeout(()=>{setTrace(items=>[...items,{kind:"FAILURE",text:"Backend required for physical execution",tone:"bad"}]);setRunning(false)},300);return}const response=await fetch(`${API_URL}/api/sessions/${sessionId}/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:prompt.trim()})});if(!response.ok){setRunning(false);setTrace(items=>[...items,{kind:"FAILURE",text:`Run rejected (${response.status})`,tone:"bad"}])}}
 async function stopTask(){if(!sessionId)return;if(mode==="backend")await fetch(`${API_URL}/api/sessions/${sessionId}/stop`,{method:"POST"});setRunning(false)}
 async function resetTask(){if(!sessionId||mode!=="backend")return;await fetch(`${API_URL}/api/sessions/${sessionId}/reset`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seed:Math.floor(Math.random()*10000)})});setVla({queue:0,latency:0,raw:[],safe:[],events:[]});setRunning(false);setCameraVersion(v=>v+1);setTrace([{kind:"SYSTEM",text:"Randomized scene reset"}])}
 const physics=sceneState?.physics_metrics,joints=sceneState?.robot.joints??[];
 return <main className="shell">
  <header className="topbar"><div className="brand"><span className="brandMark">PA</span><div><h1>Physical AI Playground</h1><p>SO-101 · MuJoCo · SmolVLA · Gemini Robotics ER2</p></div></div><div className="headerActions"><span className={`status ${online?"":"offline"}`}><i/> {online?"Simulation online":"Connecting"}</span><button className="ghostButton" type="button" onClick={resetTask} disabled={!online}>Reset scene</button></div></header>
  <section className="modeBar">{PUBLIC_DEMO?<><div><b>Robot</b><span className="staticChoice">SO-101</span></div><div><b>Controller</b><Choice value="vla" current={controller} label="VLA" onClick={setController}/><Choice value="hybrid" current={controller} label="ER2 + VLA" onClick={setController}/></div><div><b>VLA</b><span className="staticChoice">SmolVLA</span></div><div><b>Physics</b><span className="staticChoice">MuJoCo</span></div><div><b>Grasp</b><span className="staticChoice">Physics</span></div></>:<><div><b>Robot</b><Choice value="so101" current={robot} label="SO-101" onClick={v=>setRobot(v)}/><Choice value="panda" current={robot} label="Panda Legacy" onClick={v=>{setRobot(v);setController("classical")}}/></div><div><b>Controller</b><Choice value="classical" current={controller} label="Classical" onClick={setController}/><Choice value="vla" current={controller} label="VLA" onClick={v=>setController(robot==="panda"?"classical":v)}/><Choice value="hybrid" current={controller} label="ER2 + VLA" onClick={v=>setController(robot==="panda"?"classical":v)}/></div><div><b>VLA</b><span className="staticChoice">SmolVLA</span></div><div><b>Physics</b><span className="staticChoice">MuJoCo</span></div><div><b>Grasp</b><Choice value="physics" current={grasp} label="Physics" onClick={setGrasp}/><Choice value="contact_attachment" current={grasp} label="Debug Attachment" onClick={setGrasp}/></div></>}</section>
  <section className="workspace"><div className="simulationPanel"><div className="panelHeading"><div><span className="eyebrow">LIVE SIMULATION</span><h2>{robot==="so101"?"SO-101":"Franka Panda Legacy"} · MuJoCo</h2></div><div className="metrics"><span>{sceneState?.physics_hz??"—"} HZ</span><span>{sceneState?.policy_fps??"—"} FPS</span><span className={provider==="gemini"?"visionMode":"mockMode"}>{controller.toUpperCase()}</span><span>{sceneState?.actuator_count??0} ACT</span></div></div><div className={`scene ${running?"isRunning":""}`}><ClientRobotScene sceneState={sceneState} running={running}/><div className="sceneLegend">{sceneState?.scene_profile==="vla_reference"?<><span><i className="redDot"/> 24 mm red block</span><span><i className="blueDot"/> fixed blue tray</span></>:<><span><i className="multiDot"/> randomized cubes</span><span><i className="blueDot"/> target box</span></>}<span>drag rotate · wheel zoom · right-drag pan</span></div><div className="cameraTag">FRAME {sceneState?.frame??0} · STEP {sceneState?.simulation_steps??0}</div></div></div>
   <aside className="sideRail"><section className="cameraPanel"><div className="sectionTitle"><div><span className="eyebrow">POLICY OBSERVATION</span><h3>Scene + wrist RGB</h3></div><span className="livePill">{online?"LIVE":"WAIT"}</span></div><div className="cameraGrid"><div className="cameraFeed">{sessionId&&mode==="backend"?<img src={`${API_URL}/api/sessions/${sessionId}/camera.png?view=scene&v=${cameraVersion}`} alt="Scene camera"/>:<div className="cameraCube"/>}<span>observation.images.scene</span></div><div className="cameraFeed">{sessionId&&mode==="backend"?<img src={`${API_URL}/api/sessions/${sessionId}/camera.png?view=wrist&v=${cameraVersion}`} alt="Robot wrist camera"/>:<div className="cameraCube"/>}<span>observation.images.wrist</span></div></div></section>
   <details className="physicsPanel" open><summary>Physics / VLA debug</summary><div className="debugGrid"><span>Policy / physics</span><b>{sceneState?.policy_fps??0} / {sceneState?.physics_hz??0} Hz</b><span>Action queue</span><b>{vla.queue}</b><span>Inference</span><b>{vla.latency.toFixed(2)} ms</b><span>Jaw contacts</span><b>{physics?.left_contact?"L✓":"L—"} {physics?.right_contact?"R✓":"R—"}</b><span>Normal force</span><b>{physics?.normal_force??0} N</b><span>Slip velocity</span><b>{physics?.object_slip_velocity??0} m/s</b><span>Grasp state</span><b>{physics?.grasp_state??"none"}</b></div><p className="jointReadout">joints [rad]: {joints.map(v=>v.toFixed(3)).join(", ")}</p><p className="jointReadout">VLA raw: {vla.raw.length?vla.raw.map(v=>v.toFixed(3)).join(", "):"—"}</p><p className="jointReadout">safe: {vla.safe.length?vla.safe.map(v=>v.toFixed(3)).join(", "):"—"}</p></details>
   <section className="tracePanel"><div className="sectionTitle"><div><span className="eyebrow">REASONING LOOP</span><h3>Agent trace</h3></div><span className="stepCount">{trace.length} events</span></div><div className="traceList">{trace.map((event,index)=><div className={`traceEvent ${event.tone??""}`} key={`${event.kind}-${index}`}><span className={`traceKind ${event.kind.toLowerCase()}`}>{event.kind}</span><p>{event.text}</p></div>)}{running&&<div className="traceEvent pending"><span className="pulse"/><p>Executing at {sceneState?.policy_fps??15} Hz</p></div>}</div></section></aside></section>
  <section className="commandBar"><div className="commandCopy"><span className="eyebrow">NATURAL LANGUAGE CONTROL</span><label htmlFor="task">Give the robot a task</label></div><div className="commandInput"><input id="task" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")runTask()}}/><button className="runButton" type="button" onClick={runTask} disabled={running||!online}>{running?"Running…":"Run task"}</button><button className="stopButton" type="button" onClick={stopTask} disabled={!running}>Stop</button></div><p className="hint">VLA runtime only receives RGB + joint state + language. Simulator ground truth is reserved for classical baseline and final verification.</p></section>
 </main>
}
